
server:
  port: 9080
  servlet:
    context-path: /app

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://ec2-174-129-254-220.compute-1.amazonaws.com:5432/ddqkmna1cfv2h
    username: wzuzpklqyhumfs
    password: da5287abef382a3dfbd71519f6dcd4187569af742669e6d1ff1e75266368a164
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    ##show-sql: true

logging:
  level:
    # Hides HHH000424: Disabling contextual LOB creation as createClob() method threw error
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: WARN